name: flutter_radio_player
description: A Flutter plugin to play streaming audio content with background support and lock screen controls.
version: 0.2.0
homepage: https://github.com/presercomp/flutter_radio_player

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.presercomp.flutter_radio_player
        pluginClass: FlutterRadioPlayerPlugin
      ios:
        pluginClass: FlutterRadioPlayerPlugin
